# 服务配置
server:
  port: 8888  # 使用新端口

# Spring配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nestdatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/,file:./src/main/resources/static/


mybatis-plus:
   configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #sql日志输出
     mapUnderscoreToCamelCase: true

jwt:
  secret: kQ3vq5K2Vc8x7y9z0X1a2B3c4D5e6F7g8H9i0J1k2L3= #token key
  expire: 3600   # 1小时 (单位：秒)
  refresh-secret: kQ3vq5K2Vc8x7y9z0X1a2B3c4D5e6F7g8H9i0J1k2L4= #rrefreshToken key
  refresh-expire: 86400  # 24小时

# 创建用户时的默认密码
DEFAULT_PASSWORD: 888888